default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: tiago
  password: tutu
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: e_commerce_development

test:
  <<: *default
  database: e_commerce_test

production:
  <<: *default
  database: e_commerce_production
  username: e_commerce
  password: <%= ENV["E_COMMERCE_DATABASE_PASSWORD"] %>
